version: 2
updates:
  - package-ecosystem: pip
    directory: /environments/ansible-min
    schedule:
      interval: weekly
  - package-ecosystem: pip
    directory: /environments/ansible-current
    schedule:
      interval: weekly
  - package-ecosystem: pip
    directory: /environments/ansible-next
    schedule:
      interval: weekly
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
